baseURL = 'https://dievyak.github.io/'
theme = "PaperMod"
languageCode = 'en-us'
title = 'My Tech Blog'

[params.author]
name = "Divya Kaliyamoorthy"
email = "divya.vk.2009@gmail.com"

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true

[params.assets]
  disableHLJS = true
